#ifndef __COMPONENT_MESH_H__
#define __COMPONENT_MESH_H__

#include "ComponentWithResource.h"
#include "Component.h"

class ResourceMesh;

class ComponentMesh : public Component
{
public:
    explicit ComponentMesh(GameObject* go);
    ~ComponentMesh();

	bool                SetResource         (UID uid);
    const ResourceMesh* GetResource         () const;
    virtual void        OnSave              (Config& config) const override;
    virtual void        OnLoad              (Config* config) override;

	void                GetBoundingBox      (AABB& box) const override;

    static Types        GetClassType        () { return Mesh; }

    bool                GetVisible          () const { return visible; }
    void                SetVisible          (bool v) { visible = v; }

    const float4x4*     UpdateSkinPalette   ();
    void                SetAutoGenerated    (bool generated) { auto_generated = generated; }

private:

	UID resource                  = 0;
    float4x4* skin_palette        = nullptr;
    const GameObject** node_cache = nullptr;
    bool visible                  = true;
    bool auto_generated           = false;
};

#endif /* __COMPONENT_MESH_H__ */
